parameters:
  toolchain: 'stable'
  virtual_machine_image: 'ubuntu-16.04'
  name: 'linux_stable'
  display_name: 'Linux (Stable)'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.display_name }}
  continueOnError: false
  pool:
    vmImage: ${{ parameters.virtual_machine_image }}
  steps:
    - template: install_rust.yml
      parameters:
        toolchain: ${{ parameters.toolchain }}
    - script: cargo build
      displayName: "Build"
    - script: cargo test
      displayName: "Test"
    - script: cargo fmt --all -- --check
      displayName: "Formatting"
